### ISSUE TITLE
We are displaying the api url which isn't handled by the express api

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [okteto/movies#58]
When we deploy this app in cloud, we show https://movies-namespace.user.dev.okteto.net/api which is not a valid endpoint of the api. We should modify this endpoint with some config or accept it in the express api in `server.js`. The latter would look something like this:
```js
      app.get("/api", (req, res, next) => {
        res.json("api is up and running")
        return;
      });
```

Or a redirect to `/api/healthz`

**Comment by pchico83** [comment]
> When we deploy this app in cloud, we show https://movies-namespace.user.dev.okteto.net/api which is not a valid endpoint of the api. We should modify this endpoint with some config or accept it in the express api in `server.js`. The latter would look something like this:
> 
> ```js
>       app.get("/api", (req, res, next) => {
>         res.json("api is up and running")
>         return;
>       });
> ```
> 
> Or a redirect to `/api/healthz`

yes please!

**Comment by gabriel-okteto** [comment]
would it be worth adding a public static file handler at that location ?

```
https://movies-gabriel-okteto.cloud.okteto.net/api/
https://github.com/okteto/movies/pull/new/feat-api-route
```

**Comment by pchico83** [comment]
I would just create the endpoints `/api/watching` and `/api/movies`.
To do that, you need to add both paths in the `Ingress` object:
https://github.com/okteto/movies/blob/main/chart/templates/ingressv1.yaml#L21

**Comment by rberrelleza** [comment]
Could we add a static response to /api instead?

**Comment by rberrelleza** [comment]
Fixed in all fronts
