### ISSUE TITLE
URL in README goes to Page Not Found

### ISSUE THREAD

**Issue by Gerst20051** [okteto/movies#62]
This is the application used for the [How to Develop an Application based on Microservices](https://okteto.com/docs/tutorials/e2e) tutorial.

https://okteto.com/docs/tutorials/e2e

<img width="512" alt="Screen Shot 2022-04-11 at 3 08 39 PM" src="https://user-images.githubusercontent.com/235372/162841583-e1b58e13-4420-4a35-9fbf-4533f0dcd6bd.png">

**Comment by rberrelleza** [comment]
Thanks for catching this up. It's fixed now.
