### ISSUE TITLE
Diagram and description don't match

### ISSUE THREAD

**Issue by rlamana** [okteto/movies#69]
@pchico83 The description doesn't match the image. The service `rentals` is not there. What should we be changing here to match, the image or the name on the description and folder?

<img width="761" alt="Screenshot 2022-05-04 at 10 21 29" src="https://user-images.githubusercontent.com/237819/166645718-8daa41ef-e04b-4e2d-aa25-e0a86810ac0d.png">

**Comment by pchico83** [comment]
@rlamana the description, I will update it
