### ISSUE TITLE
Error when clicking deploy Link

### ISSUE THREAD

**Issue by madsbuch** [okteto/movies#84]
I get the following message when clicking the deploy link:

![Screenshot from 2022-09-06 10-29-26](https://user-images.githubusercontent.com/1612807/188586523-6ea11fc6-de51-4865-a091-bff61a9dbef3.png)

**Comment by rberrelleza** [comment]
@madsbuch what OS/browser are you using?

**Comment by madsbuch** [comment]
Google Chrome on pop is 22.04

**Comment by rberrelleza** [comment]
removed the link since okteto cloud is now deprecated
