### ISSUE TITLE
The secret "mongodb" does not contain the key "mongodb-passwords"

### ISSUE THREAD

**Issue by sussdorff** [okteto/movies#95]
Irrespective where I run the deploy, it fails due to missing secret key.

Release "mongodb" does not exist. Installing it now.!  
Error: execution error at (mongodb/templates/secrets.yaml:33:24):!  
PASSWORDS ERROR: The secret "mongodb" does not contain the key "mongodb-passwords"!error executing command 'Deploy MongoDB': 
exit status 1

**Comment by rberrelleza** [comment]
Thanks for filling the issue @sussdorff. I haven't been able to replicate it. How are you deploying the app? Are you using the UI or a CLI command?

**Comment by sussdorff** [comment]
Here is what I did.

# Click the button
1. Get a private Fork and in that fork (https://github.com/sussdorff/movies) click the button
2. Okteto Environment (https://cloud.okteto.com/#/spaces/sussdorff) opens, repository is set to https://github.com/okteto/movies
3. Build works, PG + Kafka deploy, same mongodb error as above.

Branch: main

# CLI
1. Clone fork into my mac. Run `okteto deploy --build`
2. Use Github Codespaces (build off .devcontainers utilizing okteto:okteto image for the copy) 

Same result

# Ammend mongodb auth section
As auth/password is getting deprecated, I tried to use auth/passwords (with the array), but that didn't work either (same result)

**Comment by rberrelleza** [comment]
Fixed when updating to a more modern version of mongodb
